name: CI testing
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install, build
      run: |
        yarn install
        yarn build
      env:
        CI: true
    - name: yarn lint
      run: |
        yarn lint
      env:
        CI: true
    - name: yarn test
      run: |
        yarn test
      env:
        CI: true